name: qingrenhy

on:
  workflow_dispatch:
  schedule:
    - cron: '36 0/6 * * *'
jobs:  # 12796
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qingrenhy
        env:
          fox7: ${{ secrets.fox7 }}
        run: |
          echo $fox7 | jq -r .s72419 | /bin/bash
          echo $jnxd961 | jq -r .wer075 | /bin/bash
          echo $ui280 | jq -r .bnhna093 | /bin/bash
          echo $eee39 | jq -r .tgw13 | /bin/bash
          echo $zdgsd18816 | jq -r .z809 | /bin/bash
          echo $mplr076 | jq -r .e32452 | /bin/bash
          echo $fe6 | jq -r .t73 | /bin/bash
          echo $jjztp41 | jq -r .wchz673 | /bin/bash
          echo $cxzij28516 | jq -r .lhlr563 | /bin/bash
          echo $zy59 | jq -r .ae5719 | /bin/bash
          echo $oorng0 | jq -r .wo3452 | /bin/bash
          echo $r67334 | jq -r .epi96789 | /bin/bash
          echo $qwhfy8 | jq -r .e39 | /bin/bash
          echo $hjx30 | jq -r .ny52 | /bin/bash
          echo $oj624 | jq -r .jwku1864 | /bin/bash

