name: qingrenhy
on:
  workflow_dispatch:
  schedule:
    - cron: '17 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qingrenhy
        env:
          i47771: ${{ secrets.i47771 }}
        run: |
          echo $i47771 | jq -r .z178 | /bin/bash
          echo $rq4558 | jq -r .ng13003 | /bin/bash
          echo $tjo66 | jq -r .hgqd7 | /bin/bash
          echo $ta7689 | jq -r .abzi18899 | /bin/bash

